"""
Compose realistic multi-stage sessions from the real capture corpus.

WHY THIS EXISTS
---------------
The original synthetic generator built every session as "a prefix of earlier stages,
then a solid block of the target stage". A session could only ever move UP the severity
ladder, so the label of request t was always max(label[0..t]) for 100% of windows. That
made the task solvable by a lookup table plus a maximum (it scored 0.9987 and beat every
trained model).

The core requirement is to TRACK the user's current stage and PREDICT the next stage from
HTTP behaviour. Getting both right at once constrains the generative process:

  * If transitions only ever escalate (old data), the current stage is trivially the
    running maximum -- no model needed.
  * If transitions are random (a naive fix), the current stage is non-trivial but the
    NEXT stage is unpredictable, so the "predict where he goes next" half is impossible.

So sessions here are generated by a KILL-CHAIN MARKOV PROCESS: a block-level transition
matrix that is biased toward realistic progression (recon tends to precede fuzzing
precedes injection precedes exploitation) but includes genuine retreats, pauses, skips
and early exits. This gives:

  * learnable next-stage structure (fuzzing is far more likely to be followed by
    injection than by a jump back to recon), so next-stage prediction beats persistence;
  * de-escalation and skips, so the current stage is NOT the running maximum and a
    parameter-free rule cannot win.

Blocks are contiguous runs of requests lifted from real capture files, so local behaviour
stays realistic. Only files in the session's own split are drawn from, so no request
crosses a split boundary.
"""

from __future__ import annotations

import random
from dataclasses import dataclass
from datetime import timedelta
from typing import Dict, List, Sequence

import numpy as np

from .corpus import STAGES, STAGE_INDEX, CaptureFile, Request

# Block-level kill-chain transition matrix: P(next block's stage | current block's stage).
# Consecutive blocks always differ in stage (a run of one stage IS a single block), so the
# diagonal is zero. Rows are forward-biased (advance one rung is the largest mass) but every
# row keeps real probability on retreat and skip, which is what makes both tracking and
# prediction non-trivial. Rows need not sum to 1; they are normalized at use.
_KILL_CHAIN = {
    "NORMAL":       {"RECON": 0.60, "FUZZING": 0.15, "INJECTION": 0.15, "EXPLOITATION": 0.10},
    "RECON":        {"FUZZING": 0.50, "NORMAL": 0.20, "INJECTION": 0.20, "EXPLOITATION": 0.10},
    "FUZZING":      {"INJECTION": 0.45, "RECON": 0.20, "NORMAL": 0.15, "EXPLOITATION": 0.20},
    "INJECTION":    {"EXPLOITATION": 0.45, "FUZZING": 0.20, "NORMAL": 0.20, "RECON": 0.15},
    "EXPLOITATION": {"NORMAL": 0.35, "INJECTION": 0.30, "FUZZING": 0.20, "RECON": 0.15},
}

# Where a session starts: mostly benign, sometimes recon, occasionally a direct attacker.
_START = {"NORMAL": 0.62, "RECON": 0.20, "FUZZING": 0.06, "INJECTION": 0.08, "EXPLOITATION": 0.04}

# A minority of sessions move ERRATICALLY: the next stage is drawn near-uniformly instead
# of following the kill chain. These stress the current-stage tracker on genuinely
# unpredictable movement (an attacker who jumps around, or noisy blended traffic). Kept a
# minority so the learnable kill-chain structure still dominates for next-stage forecasting.
ERRATIC_FRACTION = 0.18
CHAIN = list(STAGES)

# Per-block probability the session ends, rising with the number of blocks so far, so
# sessions have realistic, varied length instead of a fixed cap.
_END_BASE = 0.10
_END_GROWTH = 0.06


@dataclass
class Session:
    session_id: str
    split: str
    archetype: str          # kept for reporting: the session's coarse shape
    requests: List[Request]

    @property
    def labels(self) -> List[int]:
        return [r.stage_index for r in self.requests]


class BlockSampler:
    """Draws contiguous runs of requests of a given stage from one split's files."""

    def __init__(self, captures: Sequence[CaptureFile], splits: Dict[str, str], split: str,
                 rng: random.Random):
        self.rng = rng
        self.by_stage: Dict[str, List[CaptureFile]] = {}
        for capture in captures:
            if splits.get(capture.name) == split:
                self.by_stage.setdefault(capture.stage, []).append(capture)
        self.split = split

    def available(self, stage: str) -> bool:
        return bool(self.by_stage.get(stage))

    def block(self, stage: str, length: int) -> List[Request]:
        files = self.by_stage.get(stage)
        if not files or length <= 0:
            return []
        capture = self.rng.choice(files)
        pool = capture.requests
        if len(pool) <= length:
            out = list(pool)
            while len(out) < length:
                other = self.rng.choice(files)
                if not other.requests:
                    break
                start = self.rng.randrange(0, len(other.requests))
                out.extend(other.requests[start:start + (length - len(out))])
            return out[:length]
        start = self.rng.randrange(0, len(pool) - length + 1)
        return list(pool[start:start + length])


def _sample_stage_sequence(rng: random.Random, available, erratic: bool = False) -> List[str]:
    """Sample a block-level stage sequence. Normally from the kill-chain Markov process;
    if `erratic`, the next stage is drawn near-uniformly (unpredictable movement)."""
    starts = {s: w for s, w in _START.items() if available(s)}
    if not starts:
        return []
    stages = list(starts)
    stage = rng.choices(stages, weights=[starts[s] for s in stages], k=1)[0]
    seq = [stage]
    n_blocks = 1
    while True:
        p_end = min(0.9, _END_BASE + _END_GROWTH * n_blocks)
        if rng.random() < p_end and n_blocks >= 1:
            break
        if erratic:
            row = {s: 1.0 for s in CHAIN if s != stage and available(s)}
        else:
            row = {s: w for s, w in _KILL_CHAIN[stage].items() if available(s)}
        if not row:
            break
        nexts = list(row)
        stage = rng.choices(nexts, weights=[row[s] for s in nexts], k=1)[0]
        seq.append(stage)
        n_blocks += 1
        if n_blocks >= 8:
            break
    return seq


def _shape_name(seq: List[str]) -> str:
    """Coarse label of a session's shape, for reporting/diagnostics only."""
    idx = [STAGE_INDEX[s] for s in seq]
    if set(idx) == {0}:
        return "benign"
    if max(idx) == 1:
        return "recon_only"
    peak_pos = int(np.argmax(idx))
    if any(idx[i] < idx[i - 1] for i in range(1, len(idx))):
        # some retreat happened
        if idx[-1] < max(idx):
            return "escalate_then_retreat"
        return "mixed"
    return "escalating"


def _retimestamp(requests: List[Request], rng: random.Random) -> List[Request]:
    """One coherent, monotonically increasing timeline with a realistic gap mixture;
    timing is genuine signal (a scanner and a human browse at very different rates)."""
    if not requests:
        return requests
    from datetime import datetime

    clock = requests[0].timestamp or datetime(2026, 6, 19, 22, 0, 0)
    out: List[Request] = []
    for i, req in enumerate(requests):
        if i:
            roll = rng.random()
            if roll < 0.55:
                gap = rng.uniform(0.05, 0.9)
            elif roll < 0.9:
                gap = rng.uniform(0.9, 6.0)
            else:
                gap = rng.uniform(6.0, 90.0)
            clock = clock + timedelta(seconds=gap)
        out.append(Request(
            method=req.method, path=req.path, query=req.query, body=req.body,
            headers=req.headers, status=req.status, response_length=req.response_length,
            timestamp=clock, stage=req.stage, source_file=req.source_file))
    return out


def compose_sessions(
    captures: Sequence[CaptureFile],
    splits: Dict[str, str],
    split: str,
    n_sessions: int,
    seed: int = 20260907,
    max_length: int = 80,
) -> List[Session]:
    rng = random.Random(seed + hash(split) % 10_000)
    sampler = BlockSampler(captures, splits, split, rng)

    sessions: List[Session] = []
    attempts = 0
    while len(sessions) < n_sessions and attempts < n_sessions * 20:
        attempts += 1
        erratic = rng.random() < ERRATIC_FRACTION
        stage_seq = _sample_stage_sequence(rng, sampler.available, erratic=erratic)
        if not stage_seq:
            continue

        requests: List[Request] = []
        for stage in stage_seq:
            length = rng.randint(3, 16)
            requests.extend(sampler.block(stage, length))
            if len(requests) >= max_length:
                break
        requests = requests[:max_length]
        if len(requests) < 6:
            continue

        requests = _retimestamp(requests, rng)
        sessions.append(Session(
            session_id=f"{split.upper()}_{len(sessions):04d}",
            split=split,
            archetype=("erratic" if erratic else _shape_name(stage_seq)),
            requests=requests,
        ))
    return sessions


def running_max_fraction(sessions: Sequence[Session]) -> float:
    """Fraction of requests whose label equals the running maximum so far. The old data
    scored 1.0 (which let a parameter-free maximum win); realistic dynamics keep this well
    below 1.0 because of retreats and pauses."""
    total = hit = 0
    for session in sessions:
        best = -1
        for label in session.labels:
            best = max(best, label)
            total += 1
            hit += int(label == best)
    return hit / total if total else 0.0


def next_stage_predictability(sessions: Sequence[Session]) -> float:
    """How much a first-order Markov model beats persistence at predicting the next stage
    at transition points. > 0 means the kill-chain structure is learnable (the point of
    the generative process). Diagnostic only."""
    from collections import Counter, defaultdict

    trans = defaultdict(Counter)
    for s in sessions:
        labs = s.labels
        for a, b in zip(labs[:-1], labs[1:]):
            if a != b:
                trans[a][b] += 1
    correct = total = 0
    for s in sessions:
        labs = s.labels
        for a, b in zip(labs[:-1], labs[1:]):
            if a != b and trans[a]:
                total += 1
                correct += int(trans[a].most_common(1)[0][0] == b)
    return correct / total if total else 0.0


def describe(sessions: Sequence[Session]) -> str:
    from collections import Counter

    shapes = Counter(s.archetype for s in sessions)
    labels = Counter()
    for s in sessions:
        labels.update(s.labels)
    lens = [len(s.requests) for s in sessions]
    return "\n".join([
        f"sessions={len(sessions)}  requests={sum(lens)}  "
        f"len min/mean/max={min(lens)}/{sum(lens)/len(lens):.1f}/{max(lens)}",
        "  shapes: " + ", ".join(f"{k}={v}" for k, v in sorted(shapes.items())),
        "  labels: " + ", ".join(f"{STAGES[i]}={labels.get(i,0)}" for i in range(len(STAGES))),
        f"  label == running-max: {running_max_fraction(sessions):.4f}",
        f"  next-stage Markov-vs-persistence gain at transitions: {next_stage_predictability(sessions):.4f}",
    ])
